# Generated by Django 4.2.6 on 2023-10-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_star_remove_feed_like_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Star',
            new_name='Bookmark',
        ),
    ]
